name: Format, types and lint check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        with:
          python-version: "3.9"

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Formatting check
        if: always()
        run: hatch run dev:black --check .

      - name: Linting
        if: always()
        run: hatch run dev:ruff check .

      - name: Type checking
        if: always()
        run: hatch run dev:mypy .