name: Publish documentation

on:
  push:
    # Trigger on all branches and all tags
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Install Hatch
        uses: pypa/hatch@install

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v5
        with:
          key: zensical-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            zensical-

      # Build the docs on PRs to verify they don't break
      - name: Verify Docs Build (on Pull Requests)
        if: github.event_name == 'pull_request'
        run: hatch run docs:build

      # Deploy Documentation dynamically for EVERY branch and tag
      - name: Deploy Documentation
        if: github.event_name == 'push'
        run: hatch run docs:deploy ${{ github.ref_name }}