name: Unit tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: self-hosted

    concurrency:
      group: uses-tvpaint
      cancel-in-progress: true

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python-version: [python39, python310, python311, python312]

    env:
      VENV_PATH: ${{ github.workspace }}/env_${{ matrix.python-version }}
      PYTHON_EXE: C:/Users/usermuster/scoop/apps/${{ matrix.python-version }}/current/python.exe

    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry in venv
        run: |
          ${{ env.PYTHON_EXE }} -m venv ${{ env.VENV_PATH }}
          ${{ env.VENV_PATH }}/Scripts/pip.exe install --quiet poetry

      - name: Installing dependencies with Poetry...
        env:
          POETRY_EXE: ${{ env.VENV_PATH }}/Scripts/poetry.exe
          POETRY_VENV: ${{ github.workspace }}/.venv
        shell: powershell
        run: |
          if (test-path ${{ env.POETRY_VENV }}) { rm -r ${{ env.POETRY_VENV }} }
          ${{ env.POETRY_EXE }} config virtualenvs.in-project true
          ${{ env.POETRY_EXE }} install --no-interaction --with test

      - name: Pytest with coverage
        run: ${{ env.VENV_PATH }}/Scripts/poetry.exe run pytest --maxfail 5 --cov=pytvpaint
